### ISSUE TITLE
2.  Title should be same as menu. The tab name should be 'List', 'Edit', 'Create'.

### ISSUE THREAD

**Issue by aminshaka** [collecteddoc/Disciplinary-Action#2]
Title should be same as menu. That means it should be dynamic. If change the menu name then title will be changed automatically.

![image](https://user-images.githubusercontent.com/52271735/61203520-6bb54a00-a70c-11e9-8ca8-1d1cb35cd626.png)

**Comment by teksoi** [comment]
fixed

**Comment by ghost** [comment]
Solved
