### ISSUE TITLE
3.  Tab changes in all pages. Please see the image and comments below

### ISSUE THREAD

**Issue by aminshaka** [collecteddoc/Disciplinary-Action#3]
1. There will be 2 tab. e.g. List & Create.
2. When user will click on the "List" tab then page will be refreshed and tab name will be changed to "List" & "Create".
3. "Back" button will be added in the create/edit page. when click on the "Back" button then page will be refreshed and tab name will be changed to "List" & "Create".
4. When user will click on the "Edit" button in the list then "Create" tab title will be changed to "Edit" tab title.
5. In Edit mode, "Save" button will be changed to "Update" button.

![image](https://user-images.githubusercontent.com/52271735/61203590-a0c19c80-a70c-11e9-9b9a-3843b2f299b2.png)

**Comment by teksoi** [comment]
fixed

**Comment by ghost** [comment]
Solved
